@uri=http://localhost:3000/admin/api

###
GET {{uri}}/setting

###
POST {{uri}}/setting
Content-Type: application/json

{
  "bg_img": "https://tse2-mm.cn.bing.net/th/id/OIP.t9c0r_B9qQUV2qPqXgXpfwHaCx?pid=Api&rs=1",
  "title": "独行",
  "desc": "小小前端开发",
  "img_url": "http://xxx",
  "content_info": "xxxxx",
  "avator_img": "http://xxx",
  "avator": "独行",
  "info": "小小前端开发"
}

###
PUT {{uri}}/setting/5fe96af63c199f1f787e51a4
Content-Type: application/json

{
  "setting_name": "Reactjs",
  "setting_desc": "Reactjs文章"
}

### 
DELETE {{uri}}/setting/5fed5e4a68850f4790a42434